import { Home } from "../components/Home";
import { Nav } from "../components/Nav";

import { SectionHero } from "../components/SectionHero";
import styles from "../styles/Home.module.css";
import { ExameResults } from "../components/ExameResults";
import { ServicesSection } from "../components/ServicesSection";
import { About } from "../components/About";
import { Footer } from "../components/Footer";

export default function App() {
  return (
    <>
      <Nav />
      <div>
        {/* <div className={styles.home_container}> */}
        <Home />

        <ServicesSection />
        {/* </div> */}
        <About />

        <Footer />
      </div>
      {/* </div> */}
    </>
  );
}

// import Head from "next/head";
// import Image from "next/image";
// // import styles from "../styles/Home.module.css";
// import {
//   MdOutlineMailOutline,
//   MdOutlineLocationOn,
//   MdOutlineWhatsapp,
// } from "react-icons/md";
// import useEmblaCarousel from "embla-carousel-react";

// export default function Home() {
//   const [emblaRef] = useEmblaCarousel();

//   return (
//     <>
//       <Head>
//         <title>LabVida</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="w-full max-w-[1246px] mx-auto bg-slate-600">
//         asd
//         <div className="bg-orange-800">asdas</div>
//       </div>
//       {/* <div>
//         <div className={styles.teste}>
//           <nav className={styles.nav}>
//             <div className={styles.header}>
//               <Image
//                 className={styles.logo}
//                 src="/logo.svg"
//                 alt="LabVida - Laboratório de Análises Clínicas"
//                 width={180}
//                 height={80}
//                 priority
//               />

//               <ul className={styles.items}>
//                 <li>
//                   <a>HOME</a>
//                 </li>
//                 <li>
//                   <a>HOME</a>
//                 </li>
//                 <li>
//                   <a>HOME</a>
//                 </li>
//                 <li>
//                   <a>HOME</a>
//                 </li>
//               </ul>
//             </div>
//           </nav>
//           <main className="w-auto">
//             <div className={styles.embla} ref={emblaRef}>
//               <div className={styles.embla__container}>
//                 <div className={styles.embla__slide}>
//                   <h1>LabVida</h1>
//                   <p>Laboratório de Análises Clínicas.</p>
//                   <button>Teste</button>
//                 </div>
//                 <div className={styles.embla__slide}>Slide 2</div>
//                 <div className={styles.embla__slide}>Slide 3</div>
//               </div>
//             </div>
//           </main>
//         </div>
//       </div>
//       {/* <main className={styles.main}>
//         <Image
//           className={styles.logo}
//           src="/logo.svg"
//           alt="LabVida - Laboratório de Análises Clínicas"
//           width={580}
//           height={380}
//           priority
//         />

//         <div className={styles.info}>
//           <div className={styles.infoItem}>
//             <MdOutlineLocationOn size={24} color="#01a298" />
//             <p>
//               Rua Oscar Lamb, 317 <br />
//               Centro - Cerro Branco, RS
//             </p>
//           </div>
//           <div className={styles.infoItem}>
//             <MdOutlineWhatsapp size={24} color="#01a298" />
//             <p>(51) 9 99469-8848</p>
//           </div>
//           <div className={styles.infoItem}>
//             <MdOutlineMailOutline size={24} color="#01a298" />
//             <p>labvidacb@gmail.com</p>
//           </div>
//         </div>
//       </main> */}
//     </>
//   );
// }
