import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  MdOutlineMailOutline,
  MdOutlineLocationOn,
  MdOutlineWhatsapp,
} from "react-icons/md";

export default function Home() {
  return (
    <>
      <Head>
        <title>LabVida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image
          className={styles.logo}
          src="/logo.svg"
          alt="LabVida - Laboratório de Análises Clínicas"
          width={580}
          height={380}
          priority
        />

        <div className={styles.info}>
          <div className={styles.infoItem}>
            <MdOutlineLocationOn size={24} color="#01a298" />
            <p>
              Rua Oscar Lamb, 317 <br />
              Centro - Cerro Branco, RS
            </p>
          </div>
          <div className={styles.infoItem}>
            <MdOutlineWhatsapp size={24} color="#01a298" />
            <p>(51) 9 99469-8848</p>
          </div>
          <div className={styles.infoItem}>
            <MdOutlineMailOutline size={24} color="#01a298" />
            <p>labvidacb@gmail.com</p>
          </div>
        </div>
      </main>
    </>
  );
}
